DeveloperOrg/force-app/main/default/objects/Async_Log__c/Async_Log__c.object-meta.xml
<CustomObject>
    <label>Async Log</label>
    <nameField>
        <label>Async Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Async Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Async_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Async Log</relationshipLabel>
    <relationshipName>Async_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Async_Log__c/fields/Logged_Date__c.field-meta.xml
<CustomField>
    <fullName>Logged_Date__c</fullName>
    <label>Logged Date</label>
    <type>DateTime</type>
</CustomField>

DeveloperOrg/force-app/main/default/classes/futureLog.cls
public class futureLog {
    @Future
    public static void logss(set<Id>conId){
        List<Async_Log__c> logs=new List<Async_Log__c>();
        for(Id contactId  :conId){
             Async_Log__c log =new Async_Log__c();
            log.Contact__c=contactId;
            log.Action__c='update contact as Inactive';
            log.Logged_Date__c=system.now();
            logs.add(log);
        }
        insert logs;
    }
}