DeveloperOrg/force-app/main/default/objects/students__c/students__c.object-meta.xml
<CustomObject>
    <label>students</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>studentss</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/students__c/fields/subject__c.field-meta.xml
<CustomField>
    <fullName>subject__c</fullName>
    <label>subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>science</fullName>
            </value>
            <value>
                <fullName>Maths</fullName>
            </value>
            <value>
                <fullName>chemistry</fullName>
            </value>
            <value>
                <fullName>physics</fullName>
            </value>
            <value>
                <fullName>Bioligy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/objects/students__c/fields/teacher__c.field-meta.xml
<CustomField>
    <fullName>teacher__c</fullName>
    <label>teacher</label>
    <referenceTo>teacher__c</referenceTo>
    <relationshipLabel>studentss</relationshipLabel>
    <relationshipName>studentss</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/students__c/fields/tution__c.field-meta.xml
<CustomField>
    <fullName>tution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tution</label>
    <type>Checkbox</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/teacher__c/teacher__c.object-meta.xml
<CustomObject>
    <label>teacher</label>
    <nameField>
        <label>teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/classes/accountupdateIndustry.cls
public class accountupdateIndustry {
    /* Public static void industryCheck(List<Account> accList, Map<id, Account> oldValue){
      set<id> accId = new set<id>();
        for(Account acc : accList){
            if(acc.Industry!=oldValue.get(acc.id).Industry){
                accId.add(acc.Id);
                
            } 
            System.debug(accId);
        } 
        List<Account> acc1 = [Select id,Industry,(Select id,Description from Contacts) From Account Where Id IN:accId];
        List<contact> conadd = new List<contact>();
        for(Account acc :acc1){
            System.debug(acc);
            for(Contact con1 :acc.Contacts){
                con1.Description = acc.Industry;
                conadd.add(con1);
                
            }
        }
                    update conadd;
}
        Public static void conMethod (List<Contact>conloop){
            List<contact>
        }*/
    public static void stuMethod (List<students__c>stulist){
        for(students__c stu :stulist){
    if( stu.teacher__c !=null && stu.subject__c=='English'){
        stu.tution__c =true;
    }
      
    }
            }
            }