DeveloperOrg/force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Registration</relationshipLabel>
    <relationshipName>Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Registration</relationshipLabel>
    <relationshipName>Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Training_Event__c/Training_Event__c.object-meta.xml
<CustomObject>
    <label>Training Event</label>
    <nameField>
        <label>TrainingEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Event</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Training_Event__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/classes/customrecord.cls
public class customrecord {
    public static void tarinrank(){
    
        
           Training_Event__c Train = New Training_Event__c();
     Train.Name ='kala';
    Train.country__c ='USA';
    insert Train;
     
        Participant__c par =New Participant__c();
        par.Name = 'priya';
        par.Email__c ='priya@123.com';
        insert par;
    }
    
    public static void rankcustom (){
           Training_Event__c Train =[SELECT Id FROM Training_Event__c WHERE Name ='kala' LIMIT 1]; 
           Participant__c par = [SELECT Id FROM Participant__c WHERE Name ='priya'LIMIT 1];
        
    Registration__c reg = New  Registration__c();
    reg.Name ='chandra';
    reg.Status__c ='Registered';
    reg.Training_Event__c =Train.Id;
    reg.Participant__c = par.Id;
    insert reg;
    }  
    
}