DeveloperOrg/force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Registration</relationshipLabel>
    <relationshipName>Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Training_Event__c.field-meta.xml
<CustomField>
    <fullName>Training_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Event</label>
    <referenceTo>Training_Event__c</referenceTo>
    <relationshipLabel>Registration</relationshipLabel>
    <relationshipName>Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Training_Event__c/Training_Event__c.object-meta.xml
<CustomObject>
    <label>Training Event</label>
    <nameField>
        <label>TrainingEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Event</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/classes/RegistrationOverviewController.cls
/**
* @File Name :  registrationOverviewController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 24, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 24, 2025 |   | Initial Version
**/

public with sharing class RegistrationOverviewController {
    @AuraEnabled(cacheable=true)
    public static List<Registration__c> getAllRegistrations(String statusFilter) {
        String query = 'SELECT Id, Status__c, Participant__r.Name, Training_Event__r.Name FROM Registration__c';
        if (!String.isBlank(statusFilter) && statusFilter != 'All') {
            query += ' WHERE Status__c = :statusFilter';
        }
        return Database.query(query);
    }
}