DeveloperOrg/force-app/main/default/objects/Service_Schedule__c/Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Service_Schedule__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Service Schedule</relationshipLabel>
    <relationshipName>Service_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Service_Schedule__c/fields/Service_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/classes/createServiceSchedule.cls
public class createServiceSchedule {

    public static void  contocreatess(List<Contract>conlist){
       List<Service_Schedule__c> serlist =New  List<Service_Schedule__c>();
        for(Contract con :conlist){
            Service_Schedule__c ser =New Service_Schedule__c();
              ser.Contract__c=con.Id;
              ser.Name= 'ServiceSchedule'+con.ContractTerm;
              ser.Service_Start_Date__c= Date.Today(); 
              ser.Service_Status__c='Yes';
              serlist.add(ser);
       }
            if (!serlist.isEmpty()) {
            insert serlist;
        }
    }
}