DeveloperOrg/force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/patient__c/patient__c.object-meta.xml
<CustomObject>
    <label>patient</label>
    <nameField>
        <label>Pasitent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/patient__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>patient</relationshipLabel>
    <relationshipName>patient</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/classes/ReassingTOAnotherDoctor.cls
public class ReassingTOAnotherDoctor {
    Public Static Void reassignPatients(List<Doctor__c>docloop){
        for(Doctor__c doc : docloop){
            
            List<patient__c>pat =[Select Id from patient__c Where Doctor__c = :doc.Id];
            
            Doctor__c fallbackdoc =[Select Id From Doctor__c Where Id not IN(Select Doctor__c from patient__c )Limit 1];
               
            for(patient__c  patients : pat){
                patients.Doctor__c = fallbackdoc.Id;
                
                Update patients;
            }
        }
    }
  
}