DeveloperOrg/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Feedback__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/classes/FeedbackFormController.cls
public class FeedbackFormController {

    @AuraEnabled
    public static Boolean isValidRegistration(Id regId) {
        if (String.isBlank(regId)) return false;

        Registration__c reg = [
            SELECT Status__c FROM Registration__c 
            WHERE Id = :regId LIMIT 1
        ];
        return reg.Status__c == 'Attended';
    }

    @AuraEnabled
   public static void submitFeedback(Id regId, string rating, String comment) {
    insert new Feedback__c(
        Registration__c = regId,
        Rating__c = rating,
        Comments__c = comment 
        );
    }

    @AuraEnabled(cacheable=true)
    public static List<Registration__c> getRegistrations() {
        return [
            SELECT Id, Name 
            FROM Registration__c 
            WHERE Status__c = 'Attended' 
            ORDER BY CreatedDate DESC
        ];
    }

}