DeveloperOrg/force-app/main/default/objects/book__c/book__c.object-meta.xml
<CustomObject>
    <label>book</label>
    <nameField>
        <label>book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/book__c/fields/date_of_making__c.field-meta.xml
<CustomField>
    <fullName>date_of_making__c</fullName>
    <label>date of making</label>
    <type>Date</type>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/classes/Customsoql.cls
public class Customsoql {
    Public static void conText(){
        List<book__c> test =[SELECT Name FROM book__c LIMIT 2 OFFSET 2];
        system.debug('test'+test);
}
    public static void custom(){
          List<book__c> cuslist =[SELECT Name FROM book__c WHERE date_of_making__c = Null];
          system.debug('cuslist:'+cuslist  );
 }
    public static void icecube(){
        
List<Feedback__c> icee = [SELECT Name, Rating__c FROM Feedback__c WHERE Rating__c IN ('3','4','5') ];
          system.debug('icee'+icee);
    }
   
}